name: CI[![CI](https://github.com/atom/flight-manual.atom.io/actions/workflows/ci.yml/badge.svg?branch=dependabot%2Fnpm_and_yarn%2Flodash-4.17.21&event=fork)](https://github.com/atom/flight-manual.atom.io/actions/workflows/ci.yml)

on: [push]

env:
  CI: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - uses: actions/setup-node@v2
        with:
          node-version: '7'
      - name: Build
        run: |
          npm install
          script/cibuild
